### ISSUE TITLE
Can i use re-tproxy lastest version in chaos-mesh v2.0.3? 

### ISSUE THREAD

**Issue by ChanKunggc** [chaos-mesh/rs-tproxy#26]

**Comment by Andrewmatilde** [comment]
Hi @ChanKunggc , I am sorry to reply you so late. The lastest version of rs-tproxy will be supported in chaos-mesh master soon after the PR [2555](https://github.com/chaos-mesh/chaos-mesh/pull/2555) be merged. We may update the changes in next version of v2.0.X soon.
