### ISSUE TITLE
please specify the required rust version

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/rs-tproxy#5]
I have tried to compile rs-tproxy with several rust version:
- nightly-2020-07-01 failed
- nightly-2021-01-01 succeed
- nightly-2021-04-01 failed

please specify one in `rust-toolchain`

**Comment by Hexilee** [comment]
it works on stable rust.

**Comment by Hexilee** [comment]
Maybe we can should find the MSRV.

**Comment by STRRL** [comment]
> it works on latest stable rust.

Not works. I have upgrade to the latest stable by `rustup toolchain install stable`, while executing `make`, it tells me:

```
$ make
cargo build --package proxy --bin proxy
   Compiling proxy v0.1.0 (/home/strrl/pingcap/projects/rs-tproxy/proxy)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> proxy/src/main.rs:1:1
  |
1 | #![feature(duration_constants)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `proxy`

To learn more, run the command again with --verbose.
make: *** [Makefile:2: build] Error 101
```

**Comment by Hexilee** [comment]
it seems you are not using the latest master branch.

**Comment by STRRL** [comment]
>it seems you are not using the latest master branch.

😅 YES.
